import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    name: v.string(),
    email: v.string(),
    subject: v.string(),
  }).index("by_subject", ["subject"]),

  startups: defineTable({
    userId: v.id("users"),
    name: v.optional(v.string()),
    idea: v.optional(v.string()),
    brainstormResult: v.optional(v.string()),
    brainstormEvaluationUrl: v.optional(v.string()),
    dashboard: v.optional(v.string()),
    scorecardEvaluationUrl: v.optional(v.string()),
    businessPlan: v.optional(v.string()),
    businessPlanEvaluationUrl: v.optional(v.string()),
    website: v.optional(v.string()),
    pitchDeckEvaluationUrl: v.optional(v.string()),
    pitchDeck: v.optional(v.string()),
    marketResearch: v.optional(v.string()),
    marketPulseEvaluationUrl: v.optional(v.string()),
    deepDiveMarketAnalysisEvaluationUrl: v.optional(v.string()),
    marketPulse: v.optional(v.string()),
    missionVisionEvaluationUrl: v.optional(v.string()),
    missionVision: v.optional(v.string()),
    brandIdentityEvaluationUrl: v.optional(v.string()),
    brandIdentity: v.optional(v.string()),
    brandNameSelected: v.optional(v.boolean()),
    competitorMatrix: v.optional(v.string()),
    customerPersonas: v.optional(v.string()),
    interviewScripts: v.optional(v.string()),
    customerValidation: v.optional(v.string()),
    userFlowDiagram: v.optional(v.string()),
    aiWireframe: v.optional(v.string()),
    aiMentor: v.optional(v.string()),
    techStack: v.optional(v.string()),
    databaseSchema: v.optional(v.string()),
    apiEndpoints: v.optional(v.string()),
    developmentRoadmap: v.optional(v.string()),
    costEstimate: v.optional(v.string()),
    pricingStrategy: v.optional(v.string()),
    marketingCopy: v.optional(v.string()),
    preLaunchWaitlist: v.optional(v.string()),
    productHuntKit: v.optional(v.string()),
    pressRelease: v.optional(v.string()),
    growthMetrics: v.optional(v.string()),
    abTestIdeas: v.optional(v.string()),
    seoStrategy: v.optional(v.string()),
    processAutomation: v.optional(v.string()),
    draftJobDescriptions: v.optional(v.string()),
    investorMatching: v.optional(v.string()),
    dueDiligenceChecklist: v.optional(v.string()),
    aiPitchCoach: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_userId", ["userId"]),

  smithWorkspaces: defineTable({
    userId: v.id("users"),
    prompt: v.string(),
    files: v.any(),
    messages: v.any(),
  }).index("by_userId", ["userId"]),
});
