// This file is auto-generated by setup actions.
// You can add new evaluation configs here by running their setup actions.

export const SCORECARD_CONFIG = {
  businessPlan: {
    projectId: "605",
    testsetId: "13880",
    metricIds: ["1749", "1750", "1751"],
  },
  brainstorm: {
    projectId: "606",
    testsetId: "13881",
    metricIds: ["1752", "1753", "1754"],
  },

  marketPulseCheck: {
    projectId: "607",
    testsetId: "13882",
    metricIds: ["1755", "1757", "1756"],
  },

  missionVision: {
    projectId: "608",
    testsetId: "13883",
    metricIds: ["1758", "1759", "1760"],
  },

  brandIdentity: {
    projectId: "609",
    testsetId: "13884",
    metricIds: ["1761", "1762", "1763"],
  },

  scorecard: {
    projectId: "610",
    testsetId: "13885",
    metricIds: ["1764", "1765", "1766"],
  },

  pitchDeck: {
    projectId: "611",
    testsetId: "13886",
    metricIds: ["1767", "1768", "1769"],
  },
};