// This file is auto-generated by setup actions.
// You can add new evaluation configs here by running their setup actions.

export const SCORECARD_CONFIG = {
  businessPlan: {
    projectId: "605",
    testsetId: "13880",
    metricIds: ["1749", "1750", "1751"],
  },
  brainstorm: {
    projectId: "606",
    testsetId: "13881",
    metricIds: ["1752", "1753", "1754"],
  },

  marketPulseCheck: {
    projectId: "607",
    testsetId: "13882",
    metricIds: ["1755", "1757", "1756"],
  },

  missionVision: {
    projectId: "608",
    testsetId: "13883",
    metricIds: ["1758", "1759", "1760"],
  },

  brandIdentity: {
    projectId: "609",
    testsetId: "13884",
    metricIds: ["1761", "1762", "1763"],
  },

  scorecard: {
    projectId: "610",
    testsetId: "13885",
    metricIds: ["1764", "1765", "1766"],
  },

  pitchDeck: {
    projectId: "611",
    testsetId: "13886",
    metricIds: ["1767", "1768", "1769"],
  },

  deepDiveMarketAnalysis: {
    projectId: "612",
    testsetId: "13887",
    metricIds: ["1770", "1771", "1772"],
  },

  competitorMatrix: {
    projectId: "613",
    testsetId: "13889",
    metricIds: ["1773", "1775", "1774"],
  },

  customerPersonas: {
    projectId: "614",
    testsetId: "13890",
    metricIds: ["1776", "1777", "1778"],
  },

  interviewScripts: {
    projectId: "615",
    testsetId: "13891",
    metricIds: ["1779","1781","1780"],
  },

  customerValidation: {
    projectId: "616",
    testsetId: "13892",
    metricIds: ["1782", "1783", "1784"],
  },

  aiMentor: {
    projectId: "617",
    testsetId: "13893",
    metricIds: ["1786","1788","1787"],
  },

  userFlowDiagram: {
    projectId: "618",
    testsetId: "13894",
    metricIds: ["1789", "1791", "1790"],
  },

  aiWireframe: {
    projectId: "619",
    testsetId: "13895",
    metricIds: ["1793", "1794", "1795"],
  },

  websitePrototype: {
    projectId: "620",
    testsetId: "13896",
    metricIds: ["1796", "1798", "1797"],
  },

  techStack: {
    projectId: "621",
    testsetId: "13897",
    metricIds: ["1799", "1801", "1800"],
  },

  databaseSchema: {
    projectId: "622",
    testsetId: "13898",
    metricIds: ["1802", "1804", "1803"],
  },

  apiEndpoints: {
    projectId: "623",
    testsetId: "13899",
    metricIds: ["1805","1806","1807"],
  },

  developmentRoadmap: {
    projectId: "624",
    testsetId: "13900",
    metricIds: ["1808", "1809", "1810"],
  },

  costEstimate: {
    projectId: "625",
    testsetId: "13901",
    metricIds: ["1811","1813","1812"],
  },

  pricingStrategy: {
    projectId: "627",
    testsetId: "13904",
    metricIds: ["1818","1820","1819"],
  },

  marketingCopy: {
    projectId: "628",
    testsetId: "13905",
    metricIds: ["1821", "1822", "1823"],
  },

  preLaunchWaitlist: {
    projectId: "629",
    testsetId: "13906",
    metricIds: ["1825", "1826", "1824"],
  },

  productHuntKit: {
    projectId: "630",
    testsetId: "13907",
    metricIds: ["1827", "1829", "1828"],
  },

  draftPressRelease: {
    projectId: "631",
    testsetId: "13908",
    metricIds: ["1830", "1833", "1832", "1831"],
  },

  identifyGrowthMetrics: {
    projectId: "632",
    testsetId: "13909",
    metricIds: ["1834", "1835", "1836"],
  },
};