// This file is auto-generated by setup actions.
// You can add new evaluation configs here by running their setup actions.

export const SCORECARD_CONFIG = {
  businessPlan: {
    projectId: "605",
    testsetId: "13880",
    metricIds: ["1749", "1750", "1751"],
  },
  brainstorm: {
    projectId: "606",
    testsetId: "13881",
    metricIds: ["1752", "1753", "1754"],
  },

  marketPulseCheck: {
    projectId: "607",
    testsetId: "13882",
    metricIds: ["1755", "1757", "1756"],
  },

  missionVision: {
    projectId: "608",
    testsetId: "13883",
    metricIds: ["1758", "1759", "1760"],
  },

  brandIdentity: {
    projectId: "609",
    testsetId: "13884",
    metricIds: ["1761", "1762", "1763"],
  },

  scorecard: {
    projectId: "610",
    testsetId: "13885",
    metricIds: ["1764", "1765", "1766"],
  },

  pitchDeck: {
    projectId: "611",
    testsetId: "13886",
    metricIds: ["1767", "1768", "1769"],
  },

  deepDiveMarketAnalysis: {
    projectId: "612",
    testsetId: "13887",
    metricIds: ["1770", "1771", "1772"],
  },

  competitorMatrix: {
    projectId: "613",
    testsetId: "13889",
    metricIds: ["1773", "1775", "1774"],
  },

  customerPersonas: {
    projectId: "614",
    testsetId: "13890",
    metricIds: ["1776", "1777", "1778"],
  },

  interviewScripts: {
    projectId: "615",
    testsetId: "13891",
    metricIds: ["1779","1781","1780"],
  },

  customerValidation: {
    projectId: "616",
    testsetId: "13892",
    metricIds: ["1782", "1783", "1784"],
  },

  aiMentor: {
    projectId: "617",
    testsetId: "13893",
    metricIds: ["1786","1788","1787"],
  },
};