import React from 'react';
import { Link } from 'react-router-dom';
import './StaticPage.css';

const HelpCenterPage: React.FC = () => {
  return (
    <div className="static-page-container">
      <div className="static-page-content">
        <h1 className="static-page-title">Help Center</h1>

        <div className="static-page-section">
          <h2 className="static-page-subtitle">Getting Started with VentureSmith</h2>
          <p>Welcome! Here’s a simple guide to bringing your idea to life:</p>
          <ol style={{ paddingLeft: '20px', marginTop: '1rem' }}>
            <li style={{ marginBottom: '0.5rem' }}><strong>Submit Your Idea:</strong> Start by entering a single sentence that describes your business concept on the main page.</li>
            <li style={{ marginBottom: '0.5rem' }}><strong>Choose a Tool:</strong> Select one of the AI-powered tools, such as Business Plan, Market Research, or Pitch Deck.</li>
            <li style={{ marginBottom: '0.5rem' }}><strong>Generate Content:</strong> Let our AI analyze your idea and generate the foundational documents for your venture.</li>
            <li style={{ marginBottom: '0.5rem' }}><strong>Review and Refine:</strong> The generated content is a strong starting point. Review it, make edits, and tailor it to your unique vision.</li>
          </ol>
        </div>

        <div className="static-page-section">
          <h2 className="static-page-subtitle">Understanding Our AI Tools</h2>
          <h3 className="font-bold mt-4">What is VentureSmith?</h3>
          <p>
            VentureSmith is an AI-powered platform designed to help entrepreneurs validate, plan, and develop their business ideas. We provide tools to generate business plans, market research, pitch decks, and more, turning your initial concept into a comprehensive business blueprint.
          </p>

          <h3 className="font-bold mt-4">How does the AI generation work?</h3>
          <p>
            You provide a core idea, and our platform uses advanced AI models, including Google's Gemini, to analyze your concept and generate detailed documents. The AI acts as a co-founder, automating the foundational work so you can focus on strategy and execution.
          </p>

           <h3 className="font-bold mt-4">What is included in the Market Research?</h3>
          <p>
            Our AI scans the web for relevant market data, competitor information, and industry trends using services like Firecrawl to provide a solid overview. While we strive for accuracy, we always recommend cross-referencing critical data with primary sources.
          </p>
        </div>

        <div className="static-page-section">
          <h2 className="static-page-subtitle">Data, Privacy, and Ownership</h2>
          <h3 className="font-bold mt-4">Is my business idea secure?</h3>
          <p>
            Yes, security is a top priority. Your data is kept private and is primarily used to generate the documents you request. We do not share your business ideas with other users. For more details, please see our <Link to="/privacy">Privacy Policy</Link>.
          </p>

          <h3 className="font-bold mt-4">Who owns the content generated by the AI?</h3>
          <p>
            You do. You own all the rights to the business plans, pitch decks, and other materials generated from your ideas. You are free to use them for any purpose, including commercial use.
          </p>
        </div>

        <div className="static-page-section">
          <h2 className="static-page-subtitle">Troubleshooting</h2>
          <h3 className="font-bold mt-4">The AI generation failed or is taking too long. What should I do?</h3>
          <p>
            Occasionally, high demand or complex requests can cause delays. Please try refreshing the page and submitting your request again. If the problem persists, try phrasing your initial idea with more clarity and conciseness.
          </p>

          <h3 className="font-bold mt-4">I'm not satisfied with the generated content.</h3>
          <p>
            The quality of the output heavily depends on the quality of the input. Try refining your business idea to be more specific about the problem you're solving, your target audience, and your unique solution. You can run the generation multiple times to explore different angles.
          </p>
        </div>

        <div className="static-page-section">
          <h2 className="static-page-subtitle">Contact Support</h2>
          <p>
            Can't find the answer you're looking for? Our team is here to help. Please reach out to us through our <Link to="/contact">Contact Page</Link> or email us directly at support@venturesmith.com. We'll get back to you as soon as possible.
          </p>
        </div>
      </div>
    </div>
  );
};

export default HelpCenterPage;
