import React from 'react';
import './StaticPage.css'; // Using a generic CSS file for similar static pages

const TermsPage: React.FC = () => {
  return (
    <div className="static-page-container">
      <div className="static-page-content">
        <h1 className="static-page-title">Terms of Service</h1>
        <div className="static-page-section">
          <p className="text-sm text-gray-500 mb-4">Last Updated: September 29, 2025</p>
          <p>
            Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the VentureSmith website (the "Service") operated by VentureSmith ("us", "we", or "our").
          </p>
        </div>
        <div className="static-page-section">
          <h2 className="static-page-subtitle">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service. This is a legally binding agreement.
          </p>
        </div>
        <div className="static-page-section">
          <h2 className="static-page-subtitle">2. Description of Service</h2>
          <p>
            VentureSmith provides users with AI-powered tools to generate business documents, market analysis, and other materials for the purpose of validating and developing business ideas. The outputs are generated by artificial intelligence and are intended for informational and planning purposes only.
          </p>
        </div>
        <div className="static-page-section">
          <h2 className="static-page-subtitle">3. User Accounts</h2>
          <p>
            When you create an account with us, you must provide information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
          </p>
        </div>
        <div className="static-page-section">
          <h2 className="static-page-subtitle">4. Intellectual Property</h2>
          <p>
            The Service and its original content (excluding content generated by users) features and functionality are and will remain the exclusive property of VentureSmith and its licensors. The content you generate remains your property, but you grant us a license to use, modify, and display it in connection with providing the Service to you.
          </p>
        </div>
        <div className="static-page-section">
          <h2 className="static-page-subtitle">5. Disclaimer</h2>
          <p>
            The information and documents generated by the Service are provided on an "as is" and "as available" basis. VentureSmith makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. The outputs should not be considered as legal, financial, or professional advice.
          </p>
          <p className="font-bold mt-4">
            You should consult with a professional advisor before making any business decisions.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
